apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: coach-vitrine
type: Opaque
data:
  # Base64 encoded values
  # postgres-user: cG9zdGdyZXM= (postgres)
  # postgres-password: eW91cl9zZWN1cmVfcGFzc3dvcmQ= (your_secure_password)
  postgres-user: cG9zdGdyZXM=
  postgres-password: eW91cl9zZWN1cmVfcGFzc3dvcmQ=
  postgres-db: Y29hY2hfdml0cmluZQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: coach-vitrine
type: Opaque
data:
  # JWT_SECRET: bXlfc3VwZXJfc2VjcmV0X2p3dF9rZXk= (my_super_secret_jwt_key)
  jwt-secret: bXlfc3VwZXJfc2VjcmV0X2p3dF9rZXk=
