apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: coach-vitrine
data:
  POSTGRES_DB: "coach_vitrine"
  POSTGRES_USER: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config
  namespace: coach-vitrine
data:
  PORT: "3001"
  NODE_ENV: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "coach_vitrine"
  DB_USER: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: posts-service-config
  namespace: coach-vitrine
data:
  PORT: "3002"
  NODE_ENV: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "coach_vitrine"
  DB_USER: "postgres"
