apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    purpose: microservices-demo
    helm.sh/chart: {{ include "coach-vitrine.chart" . }}
    app.kubernetes.io/name: {{ include "coach-vitrine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
