apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: coach-vitrine
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: coach-vitrine
  labels:
    app: users-service
spec:
  selector:
    app: users-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
  namespace: coach-vitrine
  labels:
    app: posts-service
spec:
  selector:
    app: posts-service
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: coach-vitrine
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
